# Generated by Django 5.1.7 on 2025-03-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_savedrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='diet_preference',
            field=models.CharField(blank=True, choices=[('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('pescatarian', 'Pescatarian'), ('gluten_free', 'Gluten-Free'), ('keto', 'Keto'), ('none', 'No Preference')], default='none', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ingredients_to_avoid',
            field=models.TextField(blank=True, help_text='Comma-separated list of ingredients to avoid.', null=True),
        ),
    ]
