# Generated by Django 5.1.7 on 2025-03-13 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_userprofile_hearted_recipes'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedrecipe',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='saved_recipes', to='recipes.recipe'),
            preserve_default=False,
        ),
    ]
