# Generated by Django 5.1.7 on 2025-03-15 16:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_savedrecipe_recipe'),
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedrecipe',
            unique_together={('user', 'recipe')},
        ),
    ]
