# Generated by Django 5.1.7 on 2025-03-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_savedrecipe_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedrecipe',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
