# Generated by Django 5.1.7 on 2025-03-25 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_savedrecipe_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedrecipe',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_uploaded_recipes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='savedrecipe',
            name='use_uploaded_image',
            field=models.BooleanField(default=False),
        ),
    ]
