steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--cache-from', 'us-central1-docker.pkg.dev/scrapchef-v2/cloud-run-source-deploy/scrapchef_v2:latest',
      '-t', 'us-central1-docker.pkg.dev/scrapchef-v2/cloud-run-source-deploy/scrapchef_v2:latest',
      '.'
    ]

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/scrapchef-v2/cloud-run-source-deploy/scrapchef_v2:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'scrapchef-v2',
      '--image', 'us-central1-docker.pkg.dev/scrapchef-v2/cloud-run-source-deploy/scrapchef_v2:latest',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

  # Run database migrations as a job
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run jobs deploy run-migrations \
          --image=us-central1-docker.pkg.dev/scrapchef-v2/cloud-run-source-deploy/scrapchef_v2:latest \
          --region=us-central1 \
          --command=python \
          --args=manage.py,migrate \
          --set-env-vars=DJANGO_SETTINGS_MODULE=config.settings \
          --max-retries=1 \
          --execute

images:
  - 'us-central1-docker.pkg.dev/scrapchef-v2/cloud-run-source-deploy/scrapchef_v2:latest'
