# Generated by Django 5.1.7 on 2025-03-15 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSavedRecipe',
        ),
    ]
